### ISSUE TITLE
What does this do that DBATools doesn't?

### ISSUE THREAD

**Issue by kilasuit** [sanderstad/PSDatabaseClone#40]
This seems from a very brief glance like it may have some overlap with DBATools

Perhaps in the readme you could add some additional detail as to where this would be more suited in use vs dbatools in a features table?

**Comment by sanderstad** [comment]
Thank you for taking an interest.

This module has no overlap with dbatools. There is no functionality in dbatools that does what this module does. The PSDatabaseClone module uses a couple of commands from dbatools.

In the past Chrissy and I talked about migrating this to dbatools, and theoretically this would be possible, but we came to the conclusion that it would make things a lot more complicated. The other reason is that this module and it's functionality have it's rightful place among modules like dbatools and dbops. 

Actually, a couple of commands were migrated to dbatools because they stood out of the main functionality. Those commands are the masking commands which were introduced in dbatools about a month ago.

Comparing the functionality of dbatools and PSDatabasClone functionality is like comparing apples with oranges. Yes, they're both fruit but they're completely different.

PSDatabaseClone uses dbatools for various actions and I think that symbioses works very well.
